<?php require 'templateHeader.phtml';?>

<div class="container my-5">
  <h2 class="text-center mb-4"> Recetas (<?php echo count($recipes); ?>)</h2>

  <a href="createRecipe/"> <button method ="post" type="button" class="btn btn-light">Añadir receta</button></a>

  <?php if (!empty($recipes)): ?>
    <div class="row row-cols-1 row-cols-md-3">
      <?php foreach ($recipes as $recipe): ?>
        <div class="col">
          <div class="card shadow-sm border-0" style="width: 18rem; margin: 0 auto;">
            
            <!-- Imagen -->
            <img src="https://placehold.co/400x250?text=Receta" 
                 class="card-img-top" 
                 alt="Imagen de <?php echo $recipe->title; ?>">

            <div class="card-body">
              <h5 class="card-title text-primary fw-bold">
                <?php echo $recipe->title; ?>
              </h5>

              <p class="card-text text-secondary">
                <?php echo ($recipe->content); ?>...
              </p>
            </div>

            <ul class="list-group list-group-flush">
              <li class="list-group-item">⏱️ <?php echo $recipe->time; ?></li>
              <li class="list-group-item">📅 <?php echo $recipe->date; ?></li>
              <li class="list-group-item">👩‍🍳 Usuario: <?php echo $recipe->id_user; ?></li>
            </ul>

            <div class="card-body d-flex justify-content-between">
              <a href="showRecipeById/<?=$recipe->id_recipe?>" class="btn btn-light">Ver detalles</a>
              <a href="updateRecipe/<?=$recipe->id_recipe?>" class="btn btn-light">Modificar receta</a>
              <a href="deleteRecipe/<?=$recipe->id_recipe?>" class="btn btn-light">Borrar receta</a>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  <?php else: ?>
    <div class="alert alert-info text-center mt-5">
      No hay recetas cargadas todavía
    </div>
  <?php endif; ?>
</div>



<?php require 'templateFooter.phtml'?> 
