<?php require 'templateHeader.phtml'; ?>

<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
        <form action="<?= isset($user->id_user) ? BASE_URL . 'updateUser/' . $user->id_user : BASE_URL . 'createUser' ?>" method="POST" enctype="multipart/form-data">
            <?php if (!empty($error)): ?> <!-- Muestra mensaje de error si existe -->
                <div class='alert alert-danger' role='alert'> 
                    <?= $error ?>
                </div>
            <?php endif; ?>

            <div class="form-group mb-3">
                <label for="name">Nombre:</label> 
                <input type="text" class="form-control" id="name" name="name" value="<?= isset($user->name) ? $user->name : ''; ?>" required>

                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" value="<?= isset($user->email) ? $user->email : ''; ?>" required>

                <label for="description">Descripción:</label>
                <textarea class="form-control" id="description" name="description"><?= isset($user->description) ? $user->description : ''; ?></textarea>

                <label for="age">Edad:</label>
                <input type="number" class="form-control" id="age" name="age" value="<?= isset($user->age) ? $user->age : ''; ?>" required>
            </div>
            
            <!-- Botón dinámico para agregar o editar -->
            <button type="submit" class="btn btn-warning">
              <?= isset($user->id_user) ? 'Actualizar Usuario' : 'Añadir Usuario'; ?> 
            </button>

        </form>

        <div class="mt-3">            
            <a href="<?= BASE_URL ?>showUsers" class="btn btn-secondary">Volver al listado</a>
        </div>
    </div>
</div>

<?php require 'templateFooter.phtml'; ?>
