<?php require 'templateHeader.phtml';?>

<div class="container my-5">
  <h2 class="text-center mb-4"> Recetas (<?php echo count($recipes); ?>)</h2>
    <div class="d-flex justify-content-center mt-4 mb-4">
      <a href="addRecipe/"> <button method ="post" type="button" class="btn btn-danger ">Añadir receta</button></a>
    </div>

  <div class="row row-cols-1 row-cols-md-3 g-4">
  <?php foreach ($recipes as $recipe): ?>
    <div class="col">
      <div class="card shadow-sm border-0">
        
        
        <img src="<?= $recipe->img ?>" 
             class="card-img-top" 
             alt="Imagen de <?= $recipe->title ?>"
             style="height: 180px; object-fit: cover;"> 

        <div class="card-body">
          <h5 class="card-title text-primary fw-bold"><?= $recipe->title ?></h5>
          <p class="card-text text-secondary"><?= $recipe->content ?>...</p>
        </div>

        <ul class="list-group list-group-flush">
          <li class="list-group-item">⏱️ <?= $recipe->time ?></li>
          <li class="list-group-item">📅 <?= $recipe->date ?></li>
        </ul>

        <div class="card-body d-flex justify-content-center">
          <a href="showRecipeById/<?=$recipe->id_recipe?>" class="btn btn-light">Ver detalles</a>
        </div>

      </div>
    </div>
  <?php endforeach; ?>
</div>
</div>



<?php require 'templateFooter.phtml'?> 
