<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog de Recetas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-light border-bottom shadow-sm">
        <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" 
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

       
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>home">Inicio</a>
            <a class="nav-link" href="<?= BASE_URL ?>./showUsers">Usuarios</a>
            <a class="nav-link" href="<?= BASE_URL ?>./showRecipes">Recetas</a>
          </div>
        </div>

        <!----- boton de entrar------->
          <div class="navbar-nav ms-auto "> 
            <a class="nav-link" href="<?= BASE_URL ?>./showlogIn">Login</a> 
          </div>

        <!----boton de salir--->
          <div class="navbar-nav ms-auto "> 
            <a class="nav-link" href="./logOut">Log out</a>  
          </div>
      </div>
    </nav>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>