<?php require './templates/templateHeader.phtml' ?>

<div class="d-flex justify-content-center align-items-center vh-100 bg-light">
  <form method="POST" action="logIn" class="p-4 bg-white shadow rounded" style="width: 300px;">
    <h4 class="text-center text-danger mb-4">Iniciar sesión</h4>

    <div class="mb-3">
      <label for="username" class="form-label">Usuario</label>
      <input type="text" class="form-control" id="username" name="username" required>
    </div>

    <div class="mb-3">
      <label for="password" class="form-label">Contraseña</label>
      <input type="password" class="form-control" id="password" name="password" required>
    </div>

    <button type="submit" class="btn btn-danger w-100">Entrar</button>
  </form>
</div>


<?php require './templates/templateFooter.phtml'?> 